### ISSUE TITLE
P2: 缺少订阅服务名的-D选项

### ISSUE THREAD

**Issue by panpan0000** [openinsight-proj/openinsight-helm-charts#109]
对于dataservice来说，它的订阅者 是adservice，但是虽然如下IP是adservice，但是订阅服务名不对

zhuohao说订阅方服务名还需添加一个-D

![image](https://user-images.githubusercontent.com/14049268/234186201-9aa9c4fc-7c14-4de1-83d6-53c8161ef3e3.png)

**Comment by Frapschen** [comment]
fix in v1.0.6
