### ISSUE TITLE
[webstore-demo] Need a Dubbo demo service

### ISSUE THREAD

**Issue by wilsonwu** [openinsight-proj/openinsight-helm-charts#35]

**Comment by Frapschen** [comment]
How the dubbo demo work with other service? maybe: adservice ---dubbo protocol---> a new service?

**Comment by wilsonwu** [comment]
Seems it can't work, because different framework can't work together, I think we can build a dubbo version adservice when deploy by chart, we can choose one type of adservice, need more discuss.
