### ISSUE TITLE
[webstore-demo] HOPE to have support for arm chip

### ISSUE THREAD

**Issue by SAMZONG** [openinsight-proj/openinsight-helm-charts#83]
I have an k8s cluster running in an arm environment.

![20230405231535](https://user-images.githubusercontent.com/13782141/230125934-1e7e0781-9d21-4029-8814-8f0302c2393f.png)

**Comment by JaredTan95** [comment]
we already support arm arch, https://github.com/openinsight-proj/opentelemetry-demo/pkgs/container/demo can you give some more details?

**Comment by Frapschen** [comment]
![image](https://user-images.githubusercontent.com/35491170/234498598-237e8c9f-0da4-4030-a7e4-8a2297663a93.png)

perhaps our pipeline need more test

**Comment by Frapschen** [comment]
please try the latest chart again.
